# Configuration options for your blog - customise to taste
# This file contains no secret information, so can be stored in source control (unlike database.yml)
title: My Enki Blog
url:   http://enkiblog.com
author:
  name:    Kevin Baribeau        # For copyright notice and ATOM feeds
  email:   kevin.baribeau+enki@gmail.com # Exception emails will go here, and it is used in ATOM feeds
  open_id:                  # These are used to login to the admin area
      - https://www.google.com/accounts/o8/id?id=AItOawlC4k-6As0oD6FeR5LHl5h5cUC5ujv6XAU

